"""add daily stock to products

Revision ID: 34672bd9acfc
Revises: f200914a6ea2
Create Date: 2026-02-08 19:15:08.256313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34672bd9acfc'
down_revision: Union[str, Sequence[str], None] = 'f200914a6ea2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('daily_stock', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('stock_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'stock_date')
    op.drop_column('products', 'daily_stock')
    # ### end Alembic commands ###
